//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collected
    {
        public int CollectedID { get; set; }
        public int CollectionRequestID { get; set; }
        public int NGOID { get; set; }
    
        public virtual CollectionRequest CollectionRequest { get; set; }
        public virtual NGO NGO { get; set; }
    }
}
