//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z_Hunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZerooHungerEntities : DbContext
    {
        public ZerooHungerEntities()
            : base("name=ZerooHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collected> Collecteds { get; set; }
        public virtual DbSet<CollectionRequest> CollectionRequests { get; set; }
        public virtual DbSet<NGO> NGOs { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
